### PR TITLE
Deprecate tracing options constructors using a tracer instance

### PR DESCRIPTION
**Pull request by vietj**
In favor of the VertxBuilder#withTracer along with tracer factory implementations.

### CODE REVIEW

**Comment by yeikel** [comment]
Did you mean to deprecate the `setTracingOptions` method as well? Or is that expected to continue being a valid pattern?

**Comment by vietj** [comment]
set tracing options still works, but should not be used to pass a tracer instance, options are only meant to create instance.

what is removed in 5.0 is the tracer field on the options.

**Comment by gebn** [comment]
Possibly related to @yeikel's question, is there a new recommended approach for setting tracing options with a custom `Launcher`? Previously we had:

```java
    @Override
    public void beforeStartingVertx(VertxOptions options) {
        ...
        options.setTracingOptions(new OpenTelemetryOptions(openTelemetry));
        ...
    }
```

I'm almost certainly missing something obvious, but I can't see a way to invoke `withTracer()` on the `Builder` before Vert.x is started.

**Comment by vietj** [comment]
we should most likely update the launcher to give opportunity to specify a tracer in the launcher that would also work in Vert.x 5 new launcher.

@tsegismont what is your opiinon on this ?

**Comment by tsegismont** [comment]
@gebn in Vert.x 5, it's possible to customize the `VertxBuilder` by overriding the `createVertxBuilder` hook (see https://github.com/eclipse-vertx/vertx-launcher/pull/5)

@vietj perhaps this should be backported to the `Launcher` in 4.x to make a step by step migration possible

**Comment by vietj** [comment]
seems like a good idea @tsegismont

**Comment by gebn** [comment]
Thanks @tsegismont. Sounds like we should upgrade to Vert.x 5! +1 to a 4.x backport, because there doesn't seem to be a way to do this whilst avoiding what is now a deprecated API.

**Comment by tsegismont** [comment]
@gebn You're welcome. Yeah, we hope you upgrade to Vert.x 5 and enjoy the new features :wink: 

There was kind of a backport merged this week in https://github.com/eclipse-vertx/vert.x/pull/5288

I say kind of a backport because it's not exactly what you'll have in Vert.x 5, but when the upgrade the change will be very small (usually there is only one `Launcher` per application)

**Pull request merged**
