### PR TITLE
Rewritten part of OpenTelemetry

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Context was not properly filled

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
@vietj @anuraaga @jotak sorry to bother again, but i'm having some headaches around the context handling :smile: Hopefully this is going to fix it

**Comment by vietj** [comment]
are we good to go?

**Comment by slinkydeveloper** [comment]
> are we good to go?

Not yet, I need to clean this up after using it for testing :)

**Comment by slinkydeveloper** [comment]
@vietj now we're good, wanna check this out?

**Comment by slinkydeveloper** [comment]
Ok I may have found another issue with this PR

**Pull request merged**
