### PR TITLE
Update open tracing dependencies. Remove sql related dependencies.

### PR DESCRIPTION
**Pull request by mahinshaw**
As mentioned in #2, I updated the opentracing dependencies, including Jaeger. Likewise I removed the SQL related dependencies.

### CODE REVIEW

**Comment by mahinshaw** [comment]
The existing `OpenTracingTracer` relies on two other apis that have been removed in 0.33.0 -> `Scope.span()` and `Tracer.startActive(boolean)`. I'll leave this PR here, but to update there is going to be some more work to make it possible.

**Comment by vietj** [comment]
the CI is failing due to compilation issue, do you know why ?

**Comment by mahinshaw** [comment]
@vietj Yes. It's the removal of the `Scope.span()` method, which is used in the `OpenTracingTracer` implementation. It seems the intent of scopes is moving to being explicitly about managing lifecycle of a span within a Thread or Context. The public docs on opentracing seem behind, but the [README.md](https://github.com/opentracing/opentracing-java/blob/master/README.md) seems fairly informative on the direction and intent.

What I've gathered so far is that there needs to be an implementation of a `ScopeManager` specific to vertx, because the default one uses `ThreadLocal` state. I've started work on that, and it doesn't appear too complicated. That scope manager will then be handed off to the tracer, which will managed scope transitions. The larger problem I see there is that it depends on the static call to `Vertx.currentContext()`, which I seem to remember being on the removal list for 4.0. However, it seem important to implement the scope manager. I have one I've done some preliminary work on, and can share it. I don't yet know how it fits into the existing `OpenTracingTracer`. I'm hoping to get some time to think about this and work on a PR that can be discussed.

Overall, it seems the api has made some shifts. I'm happy to discuss and work on an implementation. Would you rather me close this and open an issue to track the OpenTracing Api changes, or leave this open and discuss here?

**Comment by vietj** [comment]
can you open another issue and close this one ?

we can involve people from Jaeger tracing to review your contribution.

**Pull request closed without merging**
