### PR TITLE
Add EventBus tracing integration tests and docs

### PR DESCRIPTION
**Pull request by tsegismont**

### CODE REVIEW

**Comment by tsegismont** [comment]
@vietj the checks cannot be performed because vert.x core snapshots are only deployed after scheduled runs

**Comment by vietj** [comment]
why does it happen ?

**Comment by vietj** [comment]
I've hand deployed snapshots but I don't get why merges don't trigger anymore snapshot deployments, I'm missing somthing here

**Comment by tsegismont** [comment]
Because the workflow file has a condition for deployment that requires the
build type to be scheduled

Le mer. 27 janv. 2021 à 19:51, Julien Viet <notifications@github.com> a
écrit :

**Comment by vietj** [comment]
ok then that was unintentional

**Comment by vietj** [comment]
actually no, the condition is fine it has also push

the issue was github.repository_owner == 'vert-x3'

**Comment by vietj** [comment]
https://github.com/eclipse-vertx/vert.x/commit/f0d42bb08301087fcf73c6230f9cd25ae98196f1

**Comment by tsegismont** [comment]
@vietj thanks for the update in vert.x core. We had only failing build since then so I restarted the core CI workflow. I can't restart tracing CI workflow core snapshots are deployed. In the meantime, would you mind reviewing the content of the PR? If you approve I'll merge as soon as the build passes. Thank yu

**Review by vietj — APPROVED** [review]
LGTM

**Pull request merged**
