### PR TITLE
fix(issue 16) properly start a span to set it's start time

### PR DESCRIPTION
**Pull request by earezki**
Motivation:

As reported on issue #16 , this resolves it by starting the span.

image

### CODE REVIEW

**Comment by vietj** [comment]
we need add a test for this behavior @earezki

**Comment by earezki** [comment]
@vietj, I've added a small test, you can ran the test against the master branch. please let me know if other tests are required.

**Comment by vietj** [comment]
I think we would need a test with a duration greater than zero that would be done without the SQLclient (i.e the test would control the span duration and make sure it lasts at least a few millis)

**Comment by vietj** [comment]
@earezki ping

**Comment by earezki** [comment]
> I think we would need a test with a duration greater than zero that would be done without the SQLclient (i.e the test would control the span duration and make sure it lasts at least a few millis)

I've changed the test, however, not sure what to do for timestamp, the least is to check if it's set or not !
Let me know if you have an idea on testing the timestamp

**Comment by vietj** [comment]
it looks good @earezki

**Comment by vietj** [comment]
could you also update the test for OpenTracing to ensure it works equally well @earezki ?

**Review by tsegismont — APPROVED** [review]
LGTM. I'm going to merge and add the test for OpenTracing at the same time.

**Pull request merged**
